-- stg_rais.tb_rais_vinculos definition

-- Drop table

-- DROP TABLE stg_rais.tb_rais_vinculos;

CREATE TABLE stg_rais.tb_rais_vinculos (
	bairros_fortaleza int2 NULL,
	bairros_rj int2 NULL,
	causa_afastamento_1 int2 NULL,
	causa_afastamento_2 int2 NULL,
	causa_afastamento_3 int2 NULL,
	motivo_desligamento int2 NULL,
	cbo_ocupacao_2002 int4 NULL,
	cnae_2_0_classe int4 NULL,
	cnae_95_classe int4 NULL,
	distritos_sp int2 NULL,
	vinculo_ativo_31_12 int2 NULL,
	faixa_etaria int2 NULL,
	faixa_hora_contrat int2 NULL,
	faixa_remun_dezem_sm int2 NULL,
	faixa_remun_media_sm int2 NULL,
	faixa_tempo_emprego int2 NULL,
	escolaridade_apos_2005 int2 NULL,
	qtd_hora_contr int2 NULL,
	idade int2 NULL,
	ind_cei_vinculado int2 NULL,
	ind_simples int2 NULL,
	mes_admissao int2 NULL,
	mes_desligamento int2 NULL,
	mun_trab int4 NULL,
	municipio int4 NULL,
	nacionalidade int2 NULL,
	natureza_juridica int2 NULL,
	ind_portador_defic int2 NULL,
	qtd_dias_afastamento int2 NULL,
	raca_cor int2 NULL,
	regioes_adm_df int2 NULL,
	vl_remun_dezembro_nom numeric(15, 2) NULL,
	vl_remun_dezembro_sm numeric(15, 2) NULL,
	vl_remun_media_nom numeric(15, 2) NULL,
	vl_remun_media_sm numeric(15, 2) NULL,
	cnae_2_0_subclasse int4 NULL,
	sexo_trabalhador int2 NULL,
	tamanho_estabelecimento int2 NULL,
	tempo_emprego int2 NULL,
	tipo_admissao int2 NULL,
	tipo_estab int2 NULL,
	tipo_estab_dsc varchar(10) NULL,
	tipo_defic int2 NULL,
	tipo_vinculo int2 NULL,
	ibge_subsetor int2 NULL,
	vl_rem_janeiro_cc numeric(15, 2) NULL,
	vl_rem_fevereiro_cc numeric(15, 2) NULL,
	vl_rem_marco_cc numeric(15, 2) NULL,
	vl_rem_abril_cc numeric(15, 2) NULL,
	vl_rem_maio_cc numeric(15, 2) NULL,
	vl_rem_junho_cc numeric(15, 2) NULL,
	vl_rem_julho_cc numeric(15, 2) NULL,
	vl_rem_agosto_cc numeric(15, 2) NULL,
	vl_rem_setembro_cc numeric(15, 2) NULL,
	vl_rem_outubro_cc numeric(15, 2) NULL,
	vl_rem_novembro_cc numeric(15, 2) NULL,
	ano_chegada_brasil int2 NULL,
	ind_trab_intermitente int2 NULL,
	ind_trab_parcial int2 NULL,
	tipo_salario int2 NULL,
	vl_salario_contratual numeric(15, 2) NULL,
	uf bpchar(2) NULL,
	ano int2 NULL,
	curr_date date NULL,
	ds_owner varchar(20) NULL
)
PARTITION BY RANGE (ano);
CREATE INDEX idx_rais_vinculos_ano ON ONLY stg_rais.tb_rais_vinculos USING btree (ano);